### ISSUE TITLE
klee-output S3 bucket

### ISSUE THREAD

**Issue by JamesDavidCarr** [klee/old-klee-web#115]
The klee-output S3 bucket that's used by klee-web is on my personal AWS S3 account. I'm planning on deleting the bucket in 1 week if no-one responds, at which time it'll be free for anyone else with an AWS account to claim.

If you'd like to keep that specific bucket reply on the thread and we can arrange a time for me to delete the bucket to ensure the best chance of keeping the name.

**Comment by ccadar** [comment]
Thanks, @JamesDavidCarr .  @helicopter88 , @giacomoguerci , AFAIK, we don't need this anymore, right?

**Comment by jamesreaver** [comment]
I spoke with @helicopter88, and I think the files uploaded by Klee Web (the klee-output) are uploaded to this bucket at the moment

**Comment by ccadar** [comment]
@JamesDavidCarr , please keep it up for a while if possible, we're chatting offline about possible replacements.  If you need to delete it ASAP, let us know the deadline.  Thanks!

**Comment by JamesDavidCarr** [comment]
Is the bucket still required?

**Comment by ccadar** [comment]
Hi @JamesDavidCarr , many thanks for being patient with this.  We should be able to replace the bucket in the next few days, I'll let you know ASAP when it's done.

**Comment by ccadar** [comment]
Hi @JamesDavidCarr, the bucket has now been replaced, thanks again for being patient with this.
