### ISSUE TITLE
Freeze all dependences

### ISSUE THREAD

**Issue by andronat** [klee/old-klee-web#123]
The projects we depend on are constantly evolving and introduce breaking changes. I'll try to create a exhaustive list of all dependences that needs to be frozen. Ideally we should have a "single source of truth" that we explicitly declare all versions of every dependency. This file should be read by ansible which should generate the needed templates.

Dependences:
- KLEE Docker image
- Django dependences
- Node.JS dependences
- Frameworks (Django, PhandomJS, etc)

**Comment by Denis-Gavrielov** [comment]
Please note that PhantomJS is now replaced by Puppeteer and Jest
