### ISSUE TITLE
KLEE Web Error Running clang on vanilla example

### ISSUE THREAD

**Issue by hMihaiDavid** [klee/old-klee-web#163]
Prob. should have posted here.
[https://github.com/klee/klee/issues/1345](https://github.com/klee/klee/issues/1345)

**Comment by ccadar** [comment]
@hMihaiDavid thanks for reporting this. I think something else is at fault here, the command line looks fine for this small example.
Unfortunately, this project doesn't have an active maintainer currently (although @andronat has done an excellent job in the last year keeping the project alive), so if you or anyone else would like to help, let us know.

**Comment by ccadar** [comment]
This was now fixed by @andronat, many thanks!
