### ISSUE TITLE
`vault_password_file` problem

### ISSUE THREAD

**Issue by muchang** [klee/old-klee-web#63]
Hello, I'm a student who wants to learn from klee-web project.
I followed the guide: `Getting started on development` in README.md file
I have installed VirtualBox, Vagrant, and Ansible by apt-get.(I'm using Ubuntu14.04)
When I started the development virtual machine with the command: `vagrant up`.
I catched these error infomations:

```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

ansible provisioner:
* `vault_password_file` for the Ansible provisioner does not exist on the host system: /home/MyUserName/.klee_vault_password
```

It's may depended on the config in Vagrantfile

```
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/vagrant.yml"
    ansible.verbose = "vvvv"
    ansible.vault_password_file = "~/.klee_vault_password"
  end
```

I'm a rookie programmer, so I don't know how to solve this problem.
Would you please give me some advice?

Best regards.

**Comment by ccadar** [comment]
One currently needs a password file, this needs to be fixed.
Unfortunately, the project is not maintained anymore, so I might delete it soon.

**Comment by muchang** [comment]
Sir, Thanks for your reply.  It was a bad news.
Actually, I'm interested in how to move KLEE into the browser, so I want to learn from the klee-web project. Could you give me some advice about how to do this work or if the work is worth enough to do?

Thanks anyway.

**Comment by ccadar** [comment]
Closing, as this has now been fixed.
