### ISSUE TITLE
Use REST practices for /job/notify

### ISSUE THREAD

**Issue by andronat** [klee/old-klee-web#77]
Change how you use `channel`. Replace it with `task_id`.

**Comment by andronat** [comment]
Also include expirations in the `task_id` data when you store them in DB.

**Comment by helicopter88** [comment]
I did it like this https://github.com/helicopter88/klee-web/commit/5b9ee671ac019d1f054771922be3e88345012603
Shall I do a pull request with this commit?

**Comment by andronat** [comment]
See [here](https://docs.djangoproject.com/en/1.9/topics/http/urls/) and [here](https://github.com/klee/klee-web/blob/master/src/klee_web/frontend/urls.py#L8)
